# Generated by Django 2.0 on 2017-12-30 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
