# Generated by Django 2.0 on 2017-12-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bla', '0002_auto_20171230_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='code',
            field=models.CharField(default='1234', max_length=4),
        ),
    ]
